#!/bin/bash
# the build hook: ".openshift/action_hooks/build"
# remember to make it executable (`chmod +x .openshift/action_hooks/build`) before to run it
if [ ! -d ${OPENSHIFT_DATA_DIR}media ]; then
        mkdir -p ${OPENSHIFT_DATA_DIR}media
fi
ln -snf ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}/wsgi/static/media

###### end of file
